### ISSUE TITLE
"ImportError: cannot import name SeriesHelper" on 2.7

### ISSUE THREAD

**Issue by gnoe8307** [influxdata/influxdb-python#347]
hi there,
I'm a bit confused. 
I can't get the Serieshelper example script work on Python 2.7. When I run it I get the following message:

> "ImportError: cannot import name SeriesHelper" 

The class InfluxDBCLient is properly imported.

What's strange is that I can run the script in Pyhton3.4. I don't get the same error.

Any idea on how to get this work on 2.7?

thanks in advance
Guillaume

**Comment by gaker** [comment]
@gnoe8307 can you post some really simple example code?  I can't replicate it:

```
$ python2.7
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from influxdb.helper import SeriesHelper
>>> from influxdb import SeriesHelper
>>> 
```
